export const ROLE_PERMISSION_CACHE_PREFIX = 'role_permissions:';
export const DISTRIBUTED_LOCK_CACHE_PREFIX = 'distributed_lock:';

export const DISTRIBUTED_LOCK_CONFLICT_MESSAGE = 'Error.ConflictingOperation';

export const CACHE_TTL_SECONDS = {
  UNLIMITED: 0,
  TEN_SECONDS: 10,
  THIRTY_SECONDS: 30,
} as const;

export const DISTRIBUTED_LOCK_DEFAULT_TTL_SECONDS = CACHE_TTL_SECONDS.THIRTY_SECONDS;
export const DISTRIBUTED_LOCK_RELEASE_TIMEOUT_SECONDS = CACHE_TTL_SECONDS.TEN_SECONDS;
