DROP INDEX IF EXISTS "Device_userId_idx";
DROP INDEX IF EXISTS "UserRole_userId_roleId_idx";

ALTER TABLE "Device"
ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "RefreshToken"
ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "RefreshToken"
ALTER COLUMN "deviceId" SET NOT NULL;

ALTER TABLE "Role"
ALTER COLUMN status SET DEFAULT 'ACTIVE',
ALTER COLUMN status SET NOT NULL;